name: H6060 Experiment 2 - Requests

on:
  workflow_dispatch:
    inputs:
      sca-eclipse-steady-enabled:
        description: Enable Eclipse Steady scan (SCA)
        type: boolean
        required: false
        default: true

      sca-snyk-enabled:
        description: Enable Snyk scan (SCA)
        type: boolean
        required: false
        default: true

      sca-owasp-dependency-check-enabled:
        description: Enable OWASP Dependency Check scan (SCA)
        type: boolean
        required: false
        default: true

      sca-grype-enabled:
        description: Enable Grype scan (SCA)
        type: boolean
        required: false
        default: true

      sast-sonarqube-enabled:
          description: Enable SonarQube scan (SAST)
          type: boolean
          required: false
          default: true

      sast-semgrep-enabled:
        description: Enable Semgrep scan (SAST)
        type: boolean
        required: false
        default: true

      sast-deepsource-enabled:
        description: Enable Deepsource scan (SAST)
        type: boolean
        required: false
        default: true

      sast-horusec-enabled:
        description: Enable Horusec scan (SAST)
        type: boolean
        required: false
        default: true

      sast-codeql-enabled:
        description: Enable CodeQL scan (SAST)
        type: boolean
        required: false
        default: true

      sast-snyk-code-enabled:
        description: Enable Snyk Code scan (SAST)
        type: boolean
        required: false
        default: true

defaults:
  run:
    shell: bash

permissions:
  security-events: write

jobs:
  build-application:
    name: Build application
    runs-on: ubuntu-latest
    steps:
        # Branched from tag 2.19.0
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: 3.6
          command: pip install -U pip

      - name: Install Pip Dependencies
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/python/install-pip-dependencies@main
        with:
          extra-pip-packages: wheel setuptools pytest-xdist pytest==3.6

      - name: Install Dependencies (Make)
        run: make

      - name: Build And Upload Python Package
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/python/python-build-upload@main
        with:
          build-command: python -m setup sdist bdist_wheel
          build-directory: dist

      - name: Run Tests (Make)
        if: ${{ inputs.sast-deepsource-enabled == true }}
        run: |
          make init
          make coverage

      - name: Upload Coverage XML Report
        if: ${{ inputs.sast-deepsource-enabled == true }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: error

      - name: Create Pip Dependency Tree
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/python/pip-dependency-tree@main

      - name: Create CycloneDX SBOM
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/python/python-sbom@main

  python-scanning:
    name: Run SCA and SAST Python Scanning Workflow
    uses: seansmith39/H6060-Experiment-Resources/.github/workflows/experiment-2-python.yml@main
    needs: build-application
    secrets: inherit
    with:
      sca-eclipse-steady-enabled: ${{ inputs.sca-eclipse-steady-enabled }}
      sca-snyk-enabled: ${{ inputs.sca-snyk-enabled }}
      sca-owasp-dependency-check-enabled: ${{ inputs.sca-owasp-dependency-check-enabled }}
      sca-grype-enabled: ${{ inputs.sca-grype-enabled }}
      sast-codeql-enabled: ${{ inputs.sast-codeql-enabled }}
      sast-sonarqube-enabled: ${{ inputs.sast-sonarqube-enabled }}
      sast-semgrep-enabled: ${{ inputs.sast-semgrep-enabled }}
      sast-deepsource-enabled: ${{ inputs.sast-deepsource-enabled }}
      sast-horusec-enabled: ${{ inputs.sast-horusec-enabled }}
      sast-snyk-code-enabled: ${{ inputs.sast-snyk-code-enabled }}
      project-name: H6060-Python-requests
      sca-file-to-scan: requirements.txt
      eclipse-steady-workspace-token: 78106DF324E42C8835A0F2FB23BCEE35
      eclipse-steady-project-source-directories: requests
      build-directory: dist
